services:
  app:
    build: .
    container_name: wb-tariffs-app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: wb-tariffs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
